language: ruby
rvm:
  - 2.6
  - 2.7
  - 3.0
  - ruby-head
gemfile:
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile
  - gemfiles/rails_head.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_head.gemfile
